version: '3.8'

services:
  backend:
    build: ./mern/backend
    ports:
      - "5050:5050"
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase  # MongoDB connection string
    depends_on:
      - mongodb

  frontend:
    build: ./mern/frontend
    ports:
      - "5173:5173"
    networks:
      - mern_network
    environment:
      REACT_APP_API_URL: http://backend:5050  # Backend URL for React app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data

networks:
  mern_network:
    driver: bridge  # Custom bridge network for inter-service communication

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally
